/* CRIANDO O BANCO DE DADOS */
CREATE DATABASE CASHFLOW
DEFAULT character set utf8
DEFAULT COLLATE utf8_general_ci;

/* USANDO O BANCO DE DADOS */
USE CASHFLOW;

/* CRIANDO AS TABELAS */
CREATE TABLE PESSOA(
	IDPESSOA INT PRIMARY KEY AUTO_INCREMENT,
	TIPOPESSOA ENUM('F', 'J') NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	APELIDO VARCHAR(30),
	CPF_CNPJ VARCHAR(18) UNIQUE,
	RG VARCHAR(20),
	NASCIMENTO DATE,
	SEXO ENUM('M', 'F'),
	EMAIL VARCHAR(50)	
)DEFAULT CHARSET = UTF8 ENGINE = InnoDB;

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	ENDERECO VARCHAR(100),
	NUMERO VARCHAR(5),
	COMPLEMENTO VARCHAR(30),
	BAIRRO VARCHAR(20),
	CIDADE VARCHAR(30),
	ESTADO CHAR(2),
	CEP VARCHAR(10),
	ID_PESSOA INT UNIQUE,
	FOREIGN KEY(ID_PESSOA) REFERENCES PESSOA(IDPESSOA)
)DEFAULT CHARSET = UTF8 ENGINE = InnoDB;

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	NUMERO VARCHAR(15),
	TIPO ENUM('RES', 'COM', 'CEL'),
	ID_PESSOA INT,
	FOREIGN KEY(ID_PESSOA) REFERENCES PESSOA(IDPESSOA)
)DEFAULT CHARSET = UTF8 ENGINE = InnoDB;

CREATE TABLE TIPOCATEGORIATITULO(
	IDTIPOCATEGORIATITULO INT PRIMARY KEY AUTO_INCREMENT,
	DESCRICAO VARCHAR(20) NOT NULL	
)DEFAULT CHARSET = UTF8 ENGINE = InnoDB;

CREATE TABLE CATEGORIATITULO (
	IDCATEGORIATITULO INT PRIMARY KEY AUTO_INCREMENT,
	DESCRICAO VARCHAR(30) NOT NULL UNIQUE,
	ID_TIPOCATEGORIATITULO INT,
	FOREIGN KEY(ID_TIPOCATEGORIATITULO) REFERENCES TIPOCATEGORIATITULO(IDTIPOCATEGORIATITULO)
)DEFAULT CHARSET = UTF8 ENGINE = InnoDB;

CREATE TABLE TITULO(
	IDTITULO INT PRIMARY KEY AUTO_INCREMENT,
	TIPOTITULO ENUM('REC', 'DEP'),
	DATATITULO DATE,
	DESCRICAO VARCHAR(100) NOT NULL,
	VALOR DECIMAL(7,2),
	PAGO TINYINT(1) DEFAULT 0,
	ID_PESSOA INT,
	ID_CATEGORIATITULO INT,
	FOREIGN KEY(ID_PESSOA) REFERENCES PESSOA(IDPESSOA),
	FOREIGN KEY (ID_CATEGORIATITULO) REFERENCES CATEGORIATITULO(IDCATEGORIATITULO)	
)DEFAULT CHARSET = UTF8 ENGINE = InnoDB;

/* ADICIONANDO DADOS AS TABELAS */

INSERT INTO PESSOA VALUES(NULL, 'F', 'SOLON DIEGO GARCIA MOREIRA', 'DIEGO', '000.000.000-00', '1234567', '1985-03-01', 'M', 'SDIEGOGM@GMAIL.COM');
INSERT INTO PESSOA(TIPOPESSOA, NOME) VALUES('J', 'LOJAO RIO DO PEIXE');
INSERT INTO PESSOA(TIPOPESSOA, NOME) VALUES('J', 'CAGEPA');
INSERT INTO PESSOA(TIPOPESSOA, NOME) VALUES('J', 'BANCO DO BRASIL');
INSERT INTO PESSOA(TIPOPESSOA, NOME) VALUES('F', 'PEDRO DAVI');

INSERT INTO ENDERECO VALUES(NULL, 'RUA JOSE LEONCIO DA SILVA', '275', 'ATRAS DO IFPB', 'JARDIM PRIMAVERA II', 'CAJAZEIRAS', 'PB', '58.900-000', 1);

INSERT INTO TELEFONE VALUES
(NULL, '833531-2737', 'COM', 1),
(NULL, '833531-3752', 'RES', 1),
(NULL, '83991289751', 'CEL', 1);

INSERT INTO TIPOCATEGORIATITULO VALUES
(NULL, 'RECEBIMENTOS'),
(NULL, 'DESPESAS FIXAS'),
(NULL, 'DESPESAS VARIAVEIS'),
(NULL, 'IMPOSTOS'),
(NULL, 'PESSOA');

INSERT INTO CATEGORIATITULO VALUES
(NULL,'13° SALARIO',1),
(NULL,'ADIANTAMENTO',1),
(NULL,'AGUA E ESGOTO',2),
(NULL,'ALUGUEL',2),
(NULL,'ALVARA',4),
(NULL,'AQUISICAO DE EQUIPAMENTOS',3),
(NULL,'ASSESSORIAS E ASSOCIACOES',3),
(NULL,'ASSISTENCIA MEDICA',5),
(NULL,'ASSISTENCIA ODONTOLOGICA',5),
(NULL,'CARTORIO',3),
(NULL,'COBRANÇA',1),
(NULL,'COFINS',4),
(NULL,'COMBUSTIVEL',3),
(NULL,'COMISSAO',1),
(NULL,'COMISSAO VENDEDORES',3),
(NULL,'CONTABILIDADE',3),
(NULL,'CSLL',4),
(NULL,'DEPOSITO BANCARIO',1),
(NULL,'EMPRESTIMOS',5),
(NULL,'ENERGIA ELETRICA',2),
(NULL,'FGTS',4),
(NULL,'HORAS EXTRAS',3),
(NULL,'ICMS',4),
(NULL,'IMPOSTO DE RENDA',4),
(NULL,'INSS',4),
(NULL,'INTERNET',2),
(NULL,'INVESTIMENTOS',1),
(NULL,'IOF',4),
(NULL,'IPI',4),
(NULL,'IPTU',4),
(NULL,'IPVA',4),
(NULL,'IRPJ',4),
(NULL,'ISS',4),
(NULL,'JUROS',3),
(NULL,'LIMPEZA',3),
(NULL,'MANUTENCAO DE EQUIPAMENTOS',3),
(NULL,'MATERIAL DE ESCRITORIO',3),
(NULL,'MENSALIDADE',1),
(NULL,'PASSAGEM AEREAS',3),
(NULL,'PIS',4),
(NULL,'PUBLICIDADE',3),
(NULL,'RECISOES TRABALHISTAS',3),
(NULL,'RENDIMENTOS',1),
(NULL,'SALARIO',1),
(NULL,'SIMPLES NACIONAL',4),
(NULL,'TAXAS BANCARIAS',3),
(NULL,'TELEFONE CELULAR',2),
(NULL,'TELEFONE FIXO',2),
(NULL,'TRANSFERENCIA BANCARIA',1),
(NULL,'TRANSLADO',3),
(NULL,'VALE ALIMENTACAO',1),
(NULL,'VALE TRANSPORTE',1),
(NULL,'VENDAS',1),
(NULL,'VIAGENS',3);

INSERT INTO TITULO VALUES(NULL, 'REC', '2017-10-05', 'SALARIO DO LOJAO RIO DO PEIXE', 2000, 1, 2, 44);
INSERT INTO TITULO VALUES(NULL, 'DEP', '2017-10-06', 'PAGAMENTO DE AGUA', 54.50, 1, 3, 3);
INSERT INTO TITULO VALUES(NULL, 'DEP', '2017-10-08', 'PAGAMENTO DE EMPRESTIMO', 99.87, 1, 4, 19);
INSERT INTO TITULO VALUES(NULL, 'REC', '2017-10-10', 'PAGAMENTO DE DINHEIRO QUE EU HAVIA EMPRESTADO', 50.00, 1, 5, 38);
INSERT INTO TITULO VALUES(NULL, 'DEP', '2017-10-30', 'CONSULTORIA DE SOLON DIEGO', 250.00, 0, 1, 3);

/* MOSTRAR O VALOR DO CAIXA */
CREATE VIEW V_CAIXA
AS
	SELECT SUM(
			CASE
				WHEN TIPOTITULO = 'REC' THEN VALOR		
				ELSE
					(VALOR * -1)
			END) AS CAIXA
	FROM TITULO
	WHERE PAGO = 1;	

SELECT * FROM V_CAIXA;

/* TITULOS A RECEBER PAGO */
SELECT T.IDTITULO, T.DATATITULO, P.NOME, T.VALOR, T.PAGO
FROM TITULO T
LEFT JOIN PESSOA P
ON T.ID_PESSOA = P.IDPESSOA
WHERE T.TIPOTITULO = 'REC' 
AND PAGO = 1 
AND T.DATATITULO BETWEEN '2017-10-01' AND '2017-10-31';

/* TITULOS A RECEBER NÃO PAGOS */
SELECT T.IDTITULO, T.DATATITULO, P.NOME, T.VALOR, T.PAGO
FROM TITULO T
LEFT JOIN PESSOA P
ON T.ID_PESSOA = P.IDPESSOA
WHERE T.TIPOTITULO = 'REC' 
AND PAGO = 0 
AND T.DATATITULO BETWEEN '2017-10-01' AND '2017-10-31';

/* TITULOS A PAGAR PAGO */
SELECT T.IDTITULO, T.DATATITULO, P.NOME, T.VALOR, T.PAGO
FROM TITULO T
LEFT JOIN PESSOA P
ON T.ID_PESSOA = P.IDPESSOA
WHERE T.TIPOTITULO = 'DEP' 
AND PAGO = 1 
AND T.DATATITULO BETWEEN '2017-10-01' AND '2017-10-31';

/* TITULOS A PAGAR NÃO PAGO */
SELECT T.IDTITULO, T.DATATITULO, P.NOME, T.VALOR, T.PAGO
FROM TITULO T
LEFT JOIN PESSOA P
ON T.ID_PESSOA = P.IDPESSOA
WHERE T.TIPOTITULO = 'DEP' 
AND PAGO = 0 
AND T.DATATITULO BETWEEN '2017-10-01' AND '2017-10-31';
	
	





