/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import DAO.PessoaDAO;
import Dominio.Endereco;
import Dominio.Pessoa;
import java.awt.Color;
import java.text.SimpleDateFormat;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Natanael
 */
public class CadastrarPessoa extends javax.swing.JInternalFrame {
// comitando
    /**
     * Creates new form CadastrarPessoa
     */
    public CadastrarPessoa() {

        initComponents();

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        textoNascimento = new javax.swing.JTextField();
        jTextNome = new javax.swing.JTextField();
        TextoNome = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextEmail = new javax.swing.JTextField();
        jTextFieldRG = new javax.swing.JTextField();
        textoRG = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        texto_Apelido_NomeFantasia = new javax.swing.JTextField();
        jTextApelido = new javax.swing.JTextField();
        jComboBoxTel = new javax.swing.JComboBox<>();
        jFormattedTextTel = new javax.swing.JFormattedTextField();
        jTextField26 = new javax.swing.JTextField();
        TextoCPF_CNPJ = new javax.swing.JLabel();
        jTextCPF_CNPJ = new javax.swing.JFormattedTextField();
        jAsterisco1 = new javax.swing.JLabel();
        jAsterisco2 = new javax.swing.JLabel();
        jTextFieldSEXO = new javax.swing.JComboBox<>();
        jFormattedTextFieldNASCIMENTO = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        jTextEndereco = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextBairro = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jFormattedTextCep = new javax.swing.JFormattedTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextNumero = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextCidade = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jComboBoxUf = new javax.swing.JComboBox<>();
        jbt_Cancelar = new javax.swing.JLabel();
        jbt_Confirmar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton_PessoaFisica = new javax.swing.JRadioButton();
        jRadioButton_PessoaJuridica = new javax.swing.JRadioButton();

        setBorder(null);
        setClosable(true);
        setPreferredSize(new java.awt.Dimension(1050, 641));

        jPanel1.setBackground(new java.awt.Color(16, 106, 41));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Dados Pessoais"));

        textoNascimento.setEditable(false);
        textoNascimento.setBackground(new java.awt.Color(255, 255, 255));
        textoNascimento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoNascimento.setText("Nascimento:");
        textoNascimento.setBorder(null);

        jTextNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomeActionPerformed(evt);
            }
        });

        TextoNome.setEditable(false);
        TextoNome.setBackground(new java.awt.Color(255, 255, 255));
        TextoNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextoNome.setText("Nome:");
        TextoNome.setBorder(null);

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(255, 255, 255));
        jTextField6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField6.setText("Sexo:");
        jTextField6.setBorder(null);

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(255, 255, 255));
        jTextField7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField7.setText("E-mail:");
        jTextField7.setBorder(null);
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jTextEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextEmail.setText("exemple@exemple.com");
        jTextEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextEmailMouseClicked(evt);
            }
        });
        jTextEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEmailActionPerformed(evt);
            }
        });

        jTextFieldRG.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextFieldRG.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        textoRG.setEditable(false);
        textoRG.setBackground(new java.awt.Color(255, 255, 255));
        textoRG.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoRG.setText("RG:");
        textoRG.setBorder(null);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        texto_Apelido_NomeFantasia.setEditable(false);
        texto_Apelido_NomeFantasia.setBackground(new java.awt.Color(255, 255, 255));
        texto_Apelido_NomeFantasia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        texto_Apelido_NomeFantasia.setText("Apelido");
        texto_Apelido_NomeFantasia.setBorder(null);

        jTextApelido.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextApelido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jComboBoxTel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBoxTel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FIXO", "CELULAR", "COMERCIAL" }));

        jFormattedTextTel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            jFormattedTextTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextTel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jFormattedTextTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextTelActionPerformed(evt);
            }
        });

        jTextField26.setEditable(false);
        jTextField26.setBackground(new java.awt.Color(255, 255, 255));
        jTextField26.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField26.setText("TEL.");
        jTextField26.setBorder(null);

        TextoCPF_CNPJ.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextCPF_CNPJ.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            jTextCPF_CNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextCPF_CNPJ.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextCPF_CNPJ.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jAsterisco1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jAsterisco1.setForeground(new java.awt.Color(255, 255, 255));
        jAsterisco1.setText("*");

        jAsterisco2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jAsterisco2.setForeground(new java.awt.Color(255, 255, 255));
        jAsterisco2.setText("*");

        jTextFieldSEXO.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextFieldSEXO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        jFormattedTextFieldNASCIMENTO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jFormattedTextFieldNASCIMENTO.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(textoRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(TextoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(texto_Apelido_NomeFantasia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jComboBoxTel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jFormattedTextTel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jTextApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldSEXO, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextNome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldRG)
                                    .addComponent(jFormattedTextFieldNASCIMENTO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TextoCPF_CNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextCPF_CNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jAsterisco1)
                            .addComponent(jAsterisco2))
                        .addGap(12, 12, 12))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(TextoNome, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField6)
                            .addComponent(texto_Apelido_NomeFantasia)
                            .addComponent(jTextApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSEXO, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jAsterisco1)
                            .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textoNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(jFormattedTextFieldNASCIMENTO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldRG, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoCPF_CNPJ, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextCPF_CNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jAsterisco2)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextTel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTel)
                    .addComponent(jTextField26))
                .addGap(4, 4, 4))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Informações Para Contato"));

        jTextEndereco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextEndereco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEnderecoActionPerformed(evt);
            }
        });

        jTextField15.setEditable(false);
        jTextField15.setBackground(new java.awt.Color(255, 255, 255));
        jTextField15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField15.setText("ENDEREÇO:");
        jTextField15.setBorder(null);

        jTextField17.setEditable(false);
        jTextField17.setBackground(new java.awt.Color(255, 255, 255));
        jTextField17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField17.setText("BAIRRO:");
        jTextField17.setBorder(null);

        jTextBairro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextBairro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextBairroActionPerformed(evt);
            }
        });

        jTextField19.setEditable(false);
        jTextField19.setBackground(new java.awt.Color(255, 255, 255));
        jTextField19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField19.setText("CEP:");
        jTextField19.setBorder(null);

        jFormattedTextCep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            jFormattedTextCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextCep.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jTextField20.setEditable(false);
        jTextField20.setBackground(new java.awt.Color(255, 255, 255));
        jTextField20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField20.setText("Nº:");
        jTextField20.setBorder(null);

        jTextNumero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextNumero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNumeroActionPerformed(evt);
            }
        });

        jTextField22.setEditable(false);
        jTextField22.setBackground(new java.awt.Color(255, 255, 255));
        jTextField22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField22.setText("CIDADE:");
        jTextField22.setBorder(null);

        jTextCidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextCidade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCidadeActionPerformed(evt);
            }
        });

        jTextField24.setEditable(false);
        jTextField24.setBackground(new java.awt.Color(255, 255, 255));
        jTextField24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField24.setText("UF");
        jTextField24.setBorder(null);

        jComboBoxUf.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jComboBoxUf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jComboBoxUf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextEndereco)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jTextBairro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jTextCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jFormattedTextCep, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxUf, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(15, 15, 15))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField15, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jTextEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField17)
                    .addComponent(jTextBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField20)
                    .addComponent(jTextNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jTextField22)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField19)
                            .addComponent(jFormattedTextCep, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField24))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jComboBoxUf, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jbt_Cancelar.setBackground(new java.awt.Color(58, 126, 53));
        jbt_Cancelar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbt_Cancelar.setForeground(new java.awt.Color(255, 255, 255));
        jbt_Cancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbt_Cancelar.setText("Cancelar");
        jbt_Cancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jbt_Cancelar.setOpaque(true);
        jbt_Cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbt_CancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbt_CancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbt_CancelarMouseExited(evt);
            }
        });

        jbt_Confirmar.setBackground(new java.awt.Color(58, 126, 53));
        jbt_Confirmar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbt_Confirmar.setForeground(new java.awt.Color(255, 255, 255));
        jbt_Confirmar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbt_Confirmar.setText("Confirmar");
        jbt_Confirmar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jbt_Confirmar.setOpaque(true);
        jbt_Confirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbt_ConfirmarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbt_ConfirmarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbt_ConfirmarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jbt_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbt_Confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbt_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbt_Confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastrar Pessoa");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tipos de Pessoa");

        jRadioButton_PessoaFisica.setBackground(new java.awt.Color(16, 106, 41));
        buttonGroup1.add(jRadioButton_PessoaFisica);
        jRadioButton_PessoaFisica.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton_PessoaFisica.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton_PessoaFisica.setText("FISICA");
        jRadioButton_PessoaFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_PessoaFisicaActionPerformed(evt);
            }
        });

        jRadioButton_PessoaJuridica.setBackground(new java.awt.Color(16, 106, 41));
        buttonGroup1.add(jRadioButton_PessoaJuridica);
        jRadioButton_PessoaJuridica.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton_PessoaJuridica.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton_PessoaJuridica.setText("JURIDICA");
        jRadioButton_PessoaJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_PessoaJuridicaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel2)
                                .addGap(0, 26, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jSeparator3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jSeparator4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton_PessoaFisica)
                            .addComponent(jRadioButton_PessoaJuridica))
                        .addGap(51, 51, 51)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(384, 384, 384))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton_PessoaFisica)
                        .addGap(8, 8, 8)
                        .addComponent(jRadioButton_PessoaJuridica)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbt_ConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbt_ConfirmarMouseClicked
        ResetColor(jbt_Confirmar);
        AlterColor(jbt_Cancelar);

        //----------------------------------------------------------------------
        //VERIFICA SE OS CAMPOS ESTÃO PREENCHIDOS
        if (jTextNome.getText().equals("")){
            AlterColorAsterisco(jAsterisco1);
            JOptionPane.showMessageDialog(null, "Algum campo não foi preenchido, Verifique e tente novamente!", "aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }else{
            ResetColorAsterisco(jAsterisco1);
        }
        if (jTextCPF_CNPJ.getText().equals("   .   .   -  ")) {
            AlterColorAsterisco(jAsterisco2);
            JOptionPane.showMessageDialog(null, "Algum campo não foi preenchido, Verifique e tente novamente!", "aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }else{
            ResetColorAsterisco(jAsterisco2);
        }
        
        
//        p.setTipoPessoa((TipoPessoa) jComboBoxTiPOPESSOA.getSelectedItem());
        Pessoa pessoa = new Pessoa();
        PessoaDAO dao = new PessoaDAO();
        
        pessoa.setNome(jTextNome.getText());
        pessoa.setApelido(jTextApelido.getText());
        pessoa.setEmail(jTextEmail.getText());
        pessoa.setCpf_cnpj(jTextCPF_CNPJ.getText());
        pessoa.setRg(jTextFieldRG.getText());
        pessoa.setSexo((String) jTextFieldSEXO.getSelectedItem());
        //DATA
        //pessoa.setNascimento(jFormattedTextFieldNASCIMENTO.getDate()); 
        //dao.setVariavelAdiconal(pessoa.getNascimento());
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

        String data = dateFormat.format(jFormattedTextFieldNASCIMENTO.getDate());
        pessoa.setNascimento(data);
                
        Endereco endereco = new Endereco();
        endereco.setEndereco(jTextEndereco.getText());
        endereco.setNumero(jTextNumero.getText());
        endereco.setBairro(jTextBairro.getText());
        endereco.setCidade(jTextCidade.getText());
        endereco.setEstado(jComboBoxUf.getSelectedItem().toString());
        endereco.setCep(jFormattedTextCep.getText());
      
        jTextNome.setText(""); // setar o texto branco depois de cadastrar
        
        pessoa.setEndereco(endereco);
        PessoaDAO pessDAO = new PessoaDAO();
        if(pessDAO.create(pessoa))
            JOptionPane.showMessageDialog(this, "Usuário Cadastrado com Sucesso!");
        else JOptionPane.showMessageDialog(this, "Falha no cadastro!");

    }//GEN-LAST:event_jbt_ConfirmarMouseClicked

    private void jbt_CancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbt_CancelarMouseClicked
        ResetColor(jbt_Cancelar);
        AlterColor(jbt_Confirmar);
    }//GEN-LAST:event_jbt_CancelarMouseClicked

    private void jTextCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCidadeActionPerformed

    private void jTextNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNumeroActionPerformed

    private void jTextBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextBairroActionPerformed

    private void jTextEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEnderecoActionPerformed

    private void jFormattedTextTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextTelActionPerformed

    private void jTextEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEmailActionPerformed
        
    }//GEN-LAST:event_jTextEmailActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomeActionPerformed

    private void jRadioButton_PessoaFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_PessoaFisicaActionPerformed
        Pessoa pessoa = new Pessoa();
        
        String valor_Cpf_Cnpj;
        if (jRadioButton_PessoaFisica.isSelected() == jRadioButton_PessoaFisica.isEnabled()) {
            TextoNome.setText("Nome:");
            TextoCPF_CNPJ.setText("CPF");
            texto_Apelido_NomeFantasia.setText("Apelido:");
            textoNascimento.setText("Nascimento:");
            textoRG.setText("RG:");
          
            try {
                jTextCPF_CNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
                valor_Cpf_Cnpj = jTextCPF_CNPJ.getText();
                pessoa.setCpf_cnpj(valor_Cpf_Cnpj);
            } catch (java.text.ParseException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jRadioButton_PessoaFisicaActionPerformed

    private void jRadioButton_PessoaJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_PessoaJuridicaActionPerformed
        Pessoa pessoa = new Pessoa();
        
        String valor_Cpf_Cnpj;
        if (jRadioButton_PessoaJuridica.isSelected() == jRadioButton_PessoaJuridica.isEnabled()) {
            TextoNome.setText("Razão Social:");
            TextoCPF_CNPJ.setText("CNPJ");
            texto_Apelido_NomeFantasia.setText("Nome Fantasia:");
            textoNascimento.setText("Inicio das Atividades:");
            textoRG.setText("Inscrição Estadual:");
            try {
                jTextCPF_CNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
                valor_Cpf_Cnpj = jTextCPF_CNPJ.getText();
                pessoa.setCpf_cnpj(valor_Cpf_Cnpj);
            } catch (java.text.ParseException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jRadioButton_PessoaJuridicaActionPerformed

    private void jbt_ConfirmarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbt_ConfirmarMouseEntered
        ResetColor(jbt_Confirmar);
    }//GEN-LAST:event_jbt_ConfirmarMouseEntered

    private void jbt_ConfirmarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbt_ConfirmarMouseExited
        AlterColor(jbt_Confirmar);
    }//GEN-LAST:event_jbt_ConfirmarMouseExited

    private void jbt_CancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbt_CancelarMouseEntered
        ResetColor(jbt_Cancelar);
    }//GEN-LAST:event_jbt_CancelarMouseEntered

    private void jbt_CancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbt_CancelarMouseExited
        AlterColor(jbt_Cancelar);
    }//GEN-LAST:event_jbt_CancelarMouseExited

    private void jTextEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextEmailMouseClicked
        jTextEmail.setText("");
    }//GEN-LAST:event_jTextEmailMouseClicked

    
//------------------------------------------------------------------------------
//METODOS ALTERAR COR DOS BOTÕES AO CLICAR
    public void AlterColor(JLabel lbl) {
        lbl.setBackground(new Color(58, 126, 53)); //VERDE CLARO (PAINEL)
    }

    public void ResetColor(JLabel lbl) {
        lbl.setBackground(new Color(16, 106, 41));//VERDE ESCURO (BOTÕES)
    }
    
//------------------------------------------------------------------------------
    
     //ALTERAR CORES DOS ASTERISCOS
    public void AlterColorAsterisco(JLabel asteriscos){
        asteriscos.setForeground(new Color(255, 0, 0));//VERMELHO
    }
    public void ResetColorAsterisco(JLabel asteriscos){
        asteriscos.setForeground(new Color(255, 255, 255));//BRANCO
    }
    
//------------------------------------------------------------------------------
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TextoCPF_CNPJ;
    private javax.swing.JTextField TextoNome;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jAsterisco1;
    private javax.swing.JLabel jAsterisco2;
    private javax.swing.JComboBox<String> jComboBoxTel;
    private javax.swing.JComboBox<String> jComboBoxUf;
    private javax.swing.JFormattedTextField jFormattedTextCep;
    private com.toedter.calendar.JDateChooser jFormattedTextFieldNASCIMENTO;
    private javax.swing.JFormattedTextField jFormattedTextTel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton_PessoaFisica;
    private javax.swing.JRadioButton jRadioButton_PessoaJuridica;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextApelido;
    private javax.swing.JTextField jTextBairro;
    private javax.swing.JFormattedTextField jTextCPF_CNPJ;
    private javax.swing.JTextField jTextCidade;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextEndereco;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextFieldRG;
    private javax.swing.JComboBox<String> jTextFieldSEXO;
    private javax.swing.JTextField jTextNome;
    private javax.swing.JTextField jTextNumero;
    private javax.swing.JLabel jbt_Cancelar;
    private javax.swing.JLabel jbt_Confirmar;
    private javax.swing.JTextField textoNascimento;
    private javax.swing.JTextField textoRG;
    private javax.swing.JTextField texto_Apelido_NomeFantasia;
    // End of variables declaration//GEN-END:variables
}
