/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author amand
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form telaLogin
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        btnEntar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBottonSair = new javax.swing.JLabel();
        jBottonRegistre = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 52));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bg_principal.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-300, 0, 790, 270);

        jPanel1.setBackground(new java.awt.Color(231, 223, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel1.setText("Usuário");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        txtLogin.setBackground(new java.awt.Color(231, 223, 204));
        txtLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtLogin.setBorder(null);
        txtLogin.setPreferredSize(new java.awt.Dimension(8, 20));
        txtLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtLoginMouseEntered(evt);
            }
        });
        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });
        jPanel1.add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, 230, 34));

        txtSenha.setBackground(new java.awt.Color(231, 223, 204));
        txtSenha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSenha.setBorder(null);
        txtSenha.setPreferredSize(new java.awt.Dimension(8, 20));
        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        txtSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSenhaKeyPressed(evt);
            }
        });
        jPanel1.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 119, 230, 34));

        btnEntar.setBackground(new java.awt.Color(231, 223, 204));
        btnEntar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnEntar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEntar.setText("Entrar");
        btnEntar.setOpaque(true);
        btnEntar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEntarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEntarMouseExited(evt);
            }
        });
        jPanel1.add(btnEntar, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 175, 72, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel2.setText("Senha");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 97, -1, -1));

        jBottonSair.setBackground(new java.awt.Color(231, 223, 204));
        jBottonSair.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jBottonSair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBottonSair.setText("Sair");
        jBottonSair.setOpaque(true);
        jBottonSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBottonSairMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBottonSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBottonSairMouseExited(evt);
            }
        });
        jPanel1.add(jBottonSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 241, 54, -1));

        jBottonRegistre.setBackground(new java.awt.Color(231, 223, 204));
        jBottonRegistre.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jBottonRegistre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBottonRegistre.setText("Registre-se");
        jBottonRegistre.setOpaque(true);
        jBottonRegistre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBottonRegistreMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBottonRegistreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBottonRegistreMouseExited(evt);
            }
        });
        jPanel1.add(jBottonRegistre, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 213, 94, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 85, 230, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 159, 230, 10));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(490, 0, 250, 270);

        setSize(new java.awt.Dimension(755, 311));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public boolean checkLogin(String login, String senha) {

        return login.equals("usuario") && senha.equals("123");
    }
    private void txtSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaKeyPressed
        // TODO add your handling code here:
           if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
               
            if (this.checkLogin(txtLogin.getText(), new String(txtSenha.getPassword()))) {
                Principal telaPri = new Principal();
            telaPri.setVisible(true);
            dispose();
                
            } else {
                JOptionPane.showMessageDialog(null, "Usuário ou senha invalidos!\nTente Novamente!");
            txtLogin.setText("");
            txtSenha.setText("");
            txtLogin.grabFocus();

            }
        }
    }//GEN-LAST:event_txtSenhaKeyPressed

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void jBottonSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBottonSairMouseClicked
        setAlterColor(jBottonSair);
        setResetColor(btnEntar);
        setResetColor(jBottonRegistre);
        this.dispose();
    }//GEN-LAST:event_jBottonSairMouseClicked

    private void jBottonSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBottonSairMouseEntered
        setAlterColor(jBottonSair);
    }//GEN-LAST:event_jBottonSairMouseEntered

    private void jBottonSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBottonSairMouseExited
        setResetColor(jBottonSair);
    }//GEN-LAST:event_jBottonSairMouseExited

    private void txtLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLoginMouseEntered
        
    }//GEN-LAST:event_txtLoginMouseEntered

    private void btnEntarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntarMouseExited
        setResetColor(btnEntar);
    }//GEN-LAST:event_btnEntarMouseExited

    private void btnEntarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntarMouseEntered
        setAlterColor(btnEntar);
    }//GEN-LAST:event_btnEntarMouseEntered

    private void btnEntarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntarMouseClicked
        setAlterColor(btnEntar);
        setResetColor(jBottonRegistre);
        setResetColor(jBottonSair);
           if (this.checkLogin(txtLogin.getText(), new String(txtSenha.getPassword()))) {
                Principal telaPri = new Principal();
            telaPri.setVisible(true);
            dispose();
                
            } else {
                JOptionPane.showMessageDialog(null, "Usuário ou senha invalidos!\nTente Novamente!");
            txtLogin.setText("");
            txtSenha.setText("");
            txtLogin.grabFocus();

            }
    }//GEN-LAST:event_btnEntarMouseClicked

    private void jBottonRegistreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBottonRegistreMouseExited
        setResetColor(jBottonRegistre);
    }//GEN-LAST:event_jBottonRegistreMouseExited

    private void jBottonRegistreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBottonRegistreMouseEntered
        setAlterColor(jBottonRegistre);
    }//GEN-LAST:event_jBottonRegistreMouseEntered

    private void jBottonRegistreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBottonRegistreMouseClicked
        setResetColor(btnEntar);
        setAlterColor(jBottonRegistre);
        setResetColor(jBottonSair);
    }//GEN-LAST:event_jBottonRegistreMouseClicked

    
    
//------------------------------------------------------------------------------
    //ALTERAR COR DOS BOTÕES AO CLICAR
    public void setAlterColor(JLabel lbl){
        lbl.setBackground(new Color(157, 148, 137));//BEGE ESCURO (BOTÕES)
        lbl.setForeground(new Color(255, 255, 255));//FONTE (LETRAS) BRANCO
        }
    
    public void setResetColor(JLabel lbl){ 
        lbl.setBackground(new Color(231, 223, 204));//BEGE CLARO (PAINEL)
        lbl.setForeground(new Color (0,0,0)); // FONTE (LETRAS) PRETO
    }
//------------------------------------------------------------------------------
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnEntar;
    private javax.swing.JLabel jBottonRegistre;
    private javax.swing.JLabel jBottonSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
